services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: pmsuser
      POSTGRES_PASSWORD: pmspass
      POSTGRES_DB: pmsdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - '6380:6379'

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=pmsuser
      - DB_PASSWORD=pmspass
      - DB_DATABASE=pmsdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    ports:
      - '5173:3000' 
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    depends_on:
      - backend

volumes:
  pgdata:
